package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.sciits.blockbuster.model.BaseData;
import com.sciits.blockbuster.web.model.WebAddressTypeDetails;

/**
 * AddressTypeTbl generated by hbm2java
 */
@Entity
@Table(name = "ADDRESS_TYPE_TBL")
public class AddressTypeTbl extends BaseData {

	private int addressTypeId;
	private UserTbl userTbl;
	private String addressTypeName;
	private String addressTypeDesc;
	private Date createdDatetime;
	private Set<UserSignupTbl> userSignupTbls = new HashSet<UserSignupTbl>(0);
	private Set<AddressDetailsTbl> addressDetailsTbls = new HashSet<AddressDetailsTbl>(0);

	public AddressTypeTbl() {
	}

	public AddressTypeTbl(int addressTypeId, UserTbl userTbl, String addressTypeName, String addressTypeDesc,
			Date createdDatetime) {
		this.addressTypeId = addressTypeId;
		this.userTbl = userTbl;
		this.addressTypeName = addressTypeName;
		this.addressTypeDesc = addressTypeDesc;
		this.createdDatetime = createdDatetime;
	}

	public AddressTypeTbl(int addressTypeId, UserTbl userTbl, String addressTypeName, String addressTypeDesc,
			Date createdDatetime, Set<UserSignupTbl> userSignupTbls, Set<AddressDetailsTbl> addressDetailsTbls) {
		this.addressTypeId = addressTypeId;
		this.userTbl = userTbl;
		this.addressTypeName = addressTypeName;
		this.addressTypeDesc = addressTypeDesc;
		this.createdDatetime = createdDatetime;
		this.userSignupTbls = userSignupTbls;
		this.addressDetailsTbls = addressDetailsTbls;
	}

	@Id
	@GeneratedValue
	@Column(name = "ADDRESS_TYPE_ID", unique = true, nullable = false)
	public int getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(int addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", nullable = false)
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "ADDRESS_TYPE_NAME", nullable = false, length = 25)
	public String getAddressTypeName() {
		return this.addressTypeName;
	}

	public void setAddressTypeName(String addressTypeName) {
		this.addressTypeName = addressTypeName;
	}

	@Column(name = "ADDRESS_TYPE_DESC", nullable = false, length = 50)
	public String getAddressTypeDesc() {
		return this.addressTypeDesc;
	}

	public void setAddressTypeDesc(String addressTypeDesc) {
		this.addressTypeDesc = addressTypeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressTypeTbl")
	public Set<UserSignupTbl> getUserSignupTbls() {
		return this.userSignupTbls;
	}

	public void setUserSignupTbls(Set<UserSignupTbl> userSignupTbls) {
		this.userSignupTbls = userSignupTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressTypeTbl")
	public Set<AddressDetailsTbl> getAddressDetailsTbls() {
		return this.addressDetailsTbls;
	}

	public void setAddressDetailsTbls(Set<AddressDetailsTbl> addressDetailsTbls) {
		this.addressDetailsTbls = addressDetailsTbls;
	}
	
	@Transient
	public WebAddressTypeDetails getAddressTypeDetails(){
		WebAddressTypeDetails addressTypeDetails = new WebAddressTypeDetails();
		addressTypeDetails.setAddressTypeId(addressTypeId);
		addressTypeDetails.setAddressTypeName(addressTypeName);
		addressTypeDetails.setAddressTypeDesc(addressTypeDesc);
		return addressTypeDetails;
	}


}

