package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sciits.blockbuster.model.BaseData;

/**
 * AddressDetailsTbl generated by hbm2java
 */
@Entity
@Table(name = "ADDRESS_DETAILS_TBL")
public class AddressDetailsTbl extends BaseData {

	private int addressDetails;
	private AddressTypeTbl addressTypeTbl;
	private CountryTbl countryTbl;
	private UserTbl userTbl;
	private String streetAddress;
	private String city;
	private String zipcode;
	private Date createdDatetime;
	private Set<UserDetailsTbl> userDetailsTbls = new HashSet<UserDetailsTbl>(0);
	private Set<MbcTempTbl> mbcTempTbls = new HashSet<MbcTempTbl>(0);
	private Set<MbcRegistrtionTbl> mbcRegistrtionTbls = new HashSet<MbcRegistrtionTbl>(0);
	private Set<MbcTbl> mbcTbls = new HashSet<MbcTbl>(0);

	public AddressDetailsTbl() {
	}

	public AddressDetailsTbl(int addressDetails, AddressTypeTbl addressTypeTbl, CountryTbl countryTbl, UserTbl userTbl,
			String streetAddress, String city, String zipcode, Date createdDatetime) {
		this.addressDetails = addressDetails;
		this.addressTypeTbl = addressTypeTbl;
		this.countryTbl = countryTbl;
		this.userTbl = userTbl;
		this.streetAddress = streetAddress;
		this.city = city;
		this.zipcode = zipcode;
		this.createdDatetime = createdDatetime;
	}

	public AddressDetailsTbl(int addressDetails, AddressTypeTbl addressTypeTbl, CountryTbl countryTbl, UserTbl userTbl,
			String streetAddress, String city, String zipcode, Date createdDatetime,
			Set<UserDetailsTbl> userDetailsTbls, Set<MbcTempTbl> mbcTempTbls, Set<MbcRegistrtionTbl> mbcRegistrtionTbls,
			Set<MbcTbl> mbcTbls) {
		this.addressDetails = addressDetails;
		this.addressTypeTbl = addressTypeTbl;
		this.countryTbl = countryTbl;
		this.userTbl = userTbl;
		this.streetAddress = streetAddress;
		this.city = city;
		this.zipcode = zipcode;
		this.createdDatetime = createdDatetime;
		this.userDetailsTbls = userDetailsTbls;
		this.mbcTempTbls = mbcTempTbls;
		this.mbcRegistrtionTbls = mbcRegistrtionTbls;
		this.mbcTbls = mbcTbls;
	}

	@Id
	@GeneratedValue
	@Column(name = "ADDRESS_DETAILS", unique = true, nullable = false)
	public int getAddressDetails() {
		return this.addressDetails;
	}

	public void setAddressDetails(int addressDetails) {
		this.addressDetails = addressDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_TYPE_ID", nullable = false)
	public AddressTypeTbl getAddressTypeTbl() {
		return this.addressTypeTbl;
	}

	public void setAddressTypeTbl(AddressTypeTbl addressTypeTbl) {
		this.addressTypeTbl = addressTypeTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_ID", nullable = false)
	public CountryTbl getCountryTbl() {
		return this.countryTbl;
	}

	public void setCountryTbl(CountryTbl countryTbl) {
		this.countryTbl = countryTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", nullable = false)
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "STREET_ADDRESS", nullable = false, length = 45)
	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	@Column(name = "CITY", nullable = false, length = 25)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIPCODE", nullable = false, length = 10)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressDetailsTbl")
	public Set<UserDetailsTbl> getUserDetailsTbls() {
		return this.userDetailsTbls;
	}

	public void setUserDetailsTbls(Set<UserDetailsTbl> userDetailsTbls) {
		this.userDetailsTbls = userDetailsTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressDetailsTbl")
	public Set<MbcTempTbl> getMbcTempTbls() {
		return this.mbcTempTbls;
	}

	public void setMbcTempTbls(Set<MbcTempTbl> mbcTempTbls) {
		this.mbcTempTbls = mbcTempTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressDetailsTbl")
	public Set<MbcRegistrtionTbl> getMbcRegistrtionTbls() {
		return this.mbcRegistrtionTbls;
	}

	public void setMbcRegistrtionTbls(Set<MbcRegistrtionTbl> mbcRegistrtionTbls) {
		this.mbcRegistrtionTbls = mbcRegistrtionTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressDetailsTbl")
	public Set<MbcTbl> getMbcTbls() {
		return this.mbcTbls;
	}

	public void setMbcTbls(Set<MbcTbl> mbcTbls) {
		this.mbcTbls = mbcTbls;
	}

}

