package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sciits.blockbuster.model.BaseData;

/**
 * BusinessPurposeTbl generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_PURPOSE_TBL")
public class BusinessPurposeTbl extends BaseData {

	private int businessPurposeId;
	private UserTbl userTbl;
	private String businessPurposeCode;
	private String businessPurposeDesc;
	private Date createdDatetime;
	private Set<MbcTempTbl> mbcTempTbls = new HashSet<MbcTempTbl>(0);
	private Set<MbcRegistrtionTbl> mbcRegistrtionTbls = new HashSet<MbcRegistrtionTbl>(0);
	private Set<MbcTbl> mbcTbls = new HashSet<MbcTbl>(0);

	public BusinessPurposeTbl() {
	}

	public BusinessPurposeTbl(int businessPurposeId, UserTbl userTbl, String businessPurposeCode,
			Date createdDatetime) {
		this.businessPurposeId = businessPurposeId;
		this.userTbl = userTbl;
		this.businessPurposeCode = businessPurposeCode;
		this.createdDatetime = createdDatetime;
	}

	public BusinessPurposeTbl(int businessPurposeId, UserTbl userTbl, String businessPurposeCode,
			String businessPurposeDesc, Date createdDatetime, Set<MbcTempTbl> mbcTempTbls,
			Set<MbcRegistrtionTbl> mbcRegistrtionTbls, Set<MbcTbl> mbcTbls) {
		this.businessPurposeId = businessPurposeId;
		this.userTbl = userTbl;
		this.businessPurposeCode = businessPurposeCode;
		this.businessPurposeDesc = businessPurposeDesc;
		this.createdDatetime = createdDatetime;
		this.mbcTempTbls = mbcTempTbls;
		this.mbcRegistrtionTbls = mbcRegistrtionTbls;
		this.mbcTbls = mbcTbls;
	}

	@Id
	@GeneratedValue
	@Column(name = "BUSINESS_PURPOSE_ID", unique = true, nullable = false)
	public int getBusinessPurposeId() {
		return this.businessPurposeId;
	}

	public void setBusinessPurposeId(int businessPurposeId) {
		this.businessPurposeId = businessPurposeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", nullable = false)
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "BUSINESS_PURPOSE_CODE", nullable = false, length = 5)
	public String getBusinessPurposeCode() {
		return this.businessPurposeCode;
	}

	public void setBusinessPurposeCode(String businessPurposeCode) {
		this.businessPurposeCode = businessPurposeCode;
	}

	@Column(name = "BUSINESS_PURPOSE_DESC", length = 30)
	public String getBusinessPurposeDesc() {
		return this.businessPurposeDesc;
	}

	public void setBusinessPurposeDesc(String businessPurposeDesc) {
		this.businessPurposeDesc = businessPurposeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessPurposeTbl")
	public Set<MbcTempTbl> getMbcTempTbls() {
		return this.mbcTempTbls;
	}

	public void setMbcTempTbls(Set<MbcTempTbl> mbcTempTbls) {
		this.mbcTempTbls = mbcTempTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessPurposeTbl")
	public Set<MbcRegistrtionTbl> getMbcRegistrtionTbls() {
		return this.mbcRegistrtionTbls;
	}

	public void setMbcRegistrtionTbls(Set<MbcRegistrtionTbl> mbcRegistrtionTbls) {
		this.mbcRegistrtionTbls = mbcRegistrtionTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessPurposeTbl")
	public Set<MbcTbl> getMbcTbls() {
		return this.mbcTbls;
	}

	public void setMbcTbls(Set<MbcTbl> mbcTbls) {
		this.mbcTbls = mbcTbls;
	}

}

