package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.sciits.blockbuster.web.model.WebCountryDetails;

/**
 * CountryTbl generated by hbm2java
 */
@Entity
@Table(name = "COUNTRY_TBL")
public class CountryTbl implements java.io.Serializable {

	private int countryId;
	private UserTbl userTbl;
	private String countryName;
	private String alpha2Code;
	private String alpha3Code;
	private String numericCode;
	private Date createdDatetime;
	private Set<UserSignupTbl> userSignupTbls = new HashSet<UserSignupTbl>(0);
	private Set<ParticipantShareholderTbl> participantShareholderTbls = new HashSet<ParticipantShareholderTbl>(0);
	private Set<PrincipalShareholderTbl> principalShareholderTbls = new HashSet<PrincipalShareholderTbl>(0);
	private Set<AddressDetailsTbl> addressDetailsTbls = new HashSet<AddressDetailsTbl>(0);

	public CountryTbl() {
	}

	public CountryTbl(int countryId, UserTbl userTbl, String countryName, String alpha2Code, String alpha3Code,
			String numericCode, Date createdDatetime) {
		this.countryId = countryId;
		this.userTbl = userTbl;
		this.countryName = countryName;
		this.alpha2Code = alpha2Code;
		this.alpha3Code = alpha3Code;
		this.numericCode = numericCode;
		this.createdDatetime = createdDatetime;
	}

	public CountryTbl(int countryId, UserTbl userTbl, String countryName, String alpha2Code, String alpha3Code,
			String numericCode, Date createdDatetime, Set<UserSignupTbl> userSignupTbls,
			Set<ParticipantShareholderTbl> participantShareholderTbls,
			Set<PrincipalShareholderTbl> principalShareholderTbls, Set<AddressDetailsTbl> addressDetailsTbls) {
		this.countryId = countryId;
		this.userTbl = userTbl;
		this.countryName = countryName;
		this.alpha2Code = alpha2Code;
		this.alpha3Code = alpha3Code;
		this.numericCode = numericCode;
		this.createdDatetime = createdDatetime;
		this.userSignupTbls = userSignupTbls;
		this.participantShareholderTbls = participantShareholderTbls;
		this.principalShareholderTbls = principalShareholderTbls;
		this.addressDetailsTbls = addressDetailsTbls;
	}

	@Id
	@GeneratedValue
	@Column(name = "COUNTRY_ID", unique = true, nullable = false)
	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", nullable = false)
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "COUNTRY_NAME", nullable = false, length = 75)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "ALPHA_2_CODE", nullable = false, length = 2)
	public String getAlpha2Code() {
		return this.alpha2Code;
	}

	public void setAlpha2Code(String alpha2Code) {
		this.alpha2Code = alpha2Code;
	}

	@Column(name = "ALPHA_3_CODE", nullable = false, length = 3)
	public String getAlpha3Code() {
		return this.alpha3Code;
	}

	public void setAlpha3Code(String alpha3Code) {
		this.alpha3Code = alpha3Code;
	}

	@Column(name = "NUMERIC_CODE", nullable = false, length = 3)
	public String getNumericCode() {
		return this.numericCode;
	}

	public void setNumericCode(String numericCode) {
		this.numericCode = numericCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryTbl")
	public Set<UserSignupTbl> getUserSignupTbls() {
		return this.userSignupTbls;
	}

	public void setUserSignupTbls(Set<UserSignupTbl> userSignupTbls) {
		this.userSignupTbls = userSignupTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryTbl")
	public Set<ParticipantShareholderTbl> getParticipantShareholderTbls() {
		return this.participantShareholderTbls;
	}

	public void setParticipantShareholderTbls(Set<ParticipantShareholderTbl> participantShareholderTbls) {
		this.participantShareholderTbls = participantShareholderTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryTbl")
	public Set<PrincipalShareholderTbl> getPrincipalShareholderTbls() {
		return this.principalShareholderTbls;
	}

	public void setPrincipalShareholderTbls(Set<PrincipalShareholderTbl> principalShareholderTbls) {
		this.principalShareholderTbls = principalShareholderTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryTbl")
	public Set<AddressDetailsTbl> getAddressDetailsTbls() {
		return this.addressDetailsTbls;
	}

	public void setAddressDetailsTbls(Set<AddressDetailsTbl> addressDetailsTbls) {
		this.addressDetailsTbls = addressDetailsTbls;
	}
	
	@Transient
	public WebCountryDetails getWebCountryDetails() {
		WebCountryDetails webCountryDetails = new WebCountryDetails();
		webCountryDetails.setCountryId(countryId);
		webCountryDetails.setCountryCode(alpha2Code);
		webCountryDetails.setCountryName(countryName);
		return webCountryDetails;
	}
}

