package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FscLegislationTbl generated by hbm2java
 */
@Entity
@Table(name = "FSC_LEGISLATION_TBL")
public class FscLegislationTbl implements java.io.Serializable {

	private int fscLegislationId;
	private UserTbl userTbl;
	private String fscLegislationName;
	private Date createdDatetime;
	private Set<MbcTbl> mbcTbls = new HashSet<MbcTbl>(0);

	public FscLegislationTbl() {
	}

	public FscLegislationTbl(int fscLegislationId, UserTbl userTbl, Date createdDatetime) {
		this.fscLegislationId = fscLegislationId;
		this.userTbl = userTbl;
		this.createdDatetime = createdDatetime;
	}

	public FscLegislationTbl(int fscLegislationId, UserTbl userTbl, String fscLegislationName, Date createdDatetime,
			Set<MbcTbl> mbcTbls) {
		this.fscLegislationId = fscLegislationId;
		this.userTbl = userTbl;
		this.fscLegislationName = fscLegislationName;
		this.createdDatetime = createdDatetime;
		this.mbcTbls = mbcTbls;
	}

	@Id
	@GeneratedValue
	@Column(name = "FSC_LEGISLATION_ID", unique = true, nullable = false)
	public int getFscLegislationId() {
		return this.fscLegislationId;
	}

	public void setFscLegislationId(int fscLegislationId) {
		this.fscLegislationId = fscLegislationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", nullable = false)
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "FSC_LEGISLATION_NAME", length = 50)
	public String getFscLegislationName() {
		return this.fscLegislationName;
	}

	public void setFscLegislationName(String fscLegislationName) {
		this.fscLegislationName = fscLegislationName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fscLegislationTbl")
	public Set<MbcTbl> getMbcTbls() {
		return this.mbcTbls;
	}

	public void setMbcTbls(Set<MbcTbl> mbcTbls) {
		this.mbcTbls = mbcTbls;
	}

}

