
package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MbcCharterTbl generated by hbm2java
 */
@Entity
@Table(name = "MBC_CHARTER_TBL")
public class MbcCharterTbl implements java.io.Serializable {

	private int mbcCharterId;
	private MbcTbl mbcTbl;
	private UserTbl userTbl;
	private BigDecimal charterFeeAmt;
	private char charterFeePaidFlag;
	private BigDecimal charterAmendmentApplicationFeeAmt;
	private char charterAmendmentFeePaidFlag;
	private BigDecimal registrationFeeAmt;
	private char registrationFeePaidFlag;
	private Date createdDatetime;

	public MbcCharterTbl() {
	}

	public MbcCharterTbl(int mbcCharterId, MbcTbl mbcTbl, BigDecimal charterFeeAmt, char charterFeePaidFlag,
			BigDecimal charterAmendmentApplicationFeeAmt, char charterAmendmentFeePaidFlag,
			BigDecimal registrationFeeAmt, char registrationFeePaidFlag, Date createdDatetime) {
		this.mbcCharterId = mbcCharterId;
		this.mbcTbl = mbcTbl;
		this.charterFeeAmt = charterFeeAmt;
		this.charterFeePaidFlag = charterFeePaidFlag;
		this.charterAmendmentApplicationFeeAmt = charterAmendmentApplicationFeeAmt;
		this.charterAmendmentFeePaidFlag = charterAmendmentFeePaidFlag;
		this.registrationFeeAmt = registrationFeeAmt;
		this.registrationFeePaidFlag = registrationFeePaidFlag;
		this.createdDatetime = createdDatetime;
	}

	public MbcCharterTbl(int mbcCharterId, MbcTbl mbcTbl, UserTbl userTbl, BigDecimal charterFeeAmt,
			char charterFeePaidFlag, BigDecimal charterAmendmentApplicationFeeAmt, char charterAmendmentFeePaidFlag,
			BigDecimal registrationFeeAmt, char registrationFeePaidFlag, Date createdDatetime) {
		this.mbcCharterId = mbcCharterId;
		this.mbcTbl = mbcTbl;
		this.userTbl = userTbl;
		this.charterFeeAmt = charterFeeAmt;
		this.charterFeePaidFlag = charterFeePaidFlag;
		this.charterAmendmentApplicationFeeAmt = charterAmendmentApplicationFeeAmt;
		this.charterAmendmentFeePaidFlag = charterAmendmentFeePaidFlag;
		this.registrationFeeAmt = registrationFeeAmt;
		this.registrationFeePaidFlag = registrationFeePaidFlag;
		this.createdDatetime = createdDatetime;
	}

	@Id
	@GeneratedValue
	@Column(name = "MBC_CHARTER_ID", unique = true, nullable = false)
	public int getMbcCharterId() {
		return this.mbcCharterId;
	}

	public void setMbcCharterId(int mbcCharterId) {
		this.mbcCharterId = mbcCharterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MBC_ID", nullable = false)
	public MbcTbl getMbcTbl() {
		return this.mbcTbl;
	}

	public void setMbcTbl(MbcTbl mbcTbl) {
		this.mbcTbl = mbcTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "CHARTER_FEE_AMT", nullable = false, precision = 18)
	public BigDecimal getCharterFeeAmt() {
		return this.charterFeeAmt;
	}

	public void setCharterFeeAmt(BigDecimal charterFeeAmt) {
		this.charterFeeAmt = charterFeeAmt;
	}

	@Column(name = "CHARTER_FEE_PAID_FLAG", nullable = false, length = 1)
	public char getCharterFeePaidFlag() {
		return this.charterFeePaidFlag;
	}

	public void setCharterFeePaidFlag(char charterFeePaidFlag) {
		this.charterFeePaidFlag = charterFeePaidFlag;
	}

	@Column(name = "CHARTER_AMENDMENT_APPLICATION_FEE_AMT", nullable = false, precision = 18)
	public BigDecimal getCharterAmendmentApplicationFeeAmt() {
		return this.charterAmendmentApplicationFeeAmt;
	}

	public void setCharterAmendmentApplicationFeeAmt(BigDecimal charterAmendmentApplicationFeeAmt) {
		this.charterAmendmentApplicationFeeAmt = charterAmendmentApplicationFeeAmt;
	}

	@Column(name = "CHARTER_AMENDMENT_FEE_PAID_FLAG", nullable = false, length = 1)
	public char getCharterAmendmentFeePaidFlag() {
		return this.charterAmendmentFeePaidFlag;
	}

	public void setCharterAmendmentFeePaidFlag(char charterAmendmentFeePaidFlag) {
		this.charterAmendmentFeePaidFlag = charterAmendmentFeePaidFlag;
	}

	@Column(name = "REGISTRATION_FEE_AMT", nullable = false, precision = 18)
	public BigDecimal getRegistrationFeeAmt() {
		return this.registrationFeeAmt;
	}

	public void setRegistrationFeeAmt(BigDecimal registrationFeeAmt) {
		this.registrationFeeAmt = registrationFeeAmt;
	}

	@Column(name = "REGISTRATION_FEE_PAID_FLAG", nullable = false, length = 1)
	public char getRegistrationFeePaidFlag() {
		return this.registrationFeePaidFlag;
	}

	public void setRegistrationFeePaidFlag(char registrationFeePaidFlag) {
		this.registrationFeePaidFlag = registrationFeePaidFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

}

