package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MbcTempTbl generated by hbm2java
 */
@Entity
@Table(name = "MBC_TEMP_TBL")
public class MbcTempTbl implements java.io.Serializable {

	private int mbcTempId;
	private ParticipantShareholderTbl participantShareholderTbl;
	private UserTbl userTblByCreatedBy;
	private PrincipalShareholderTbl principalShareholderTbl;
	private BusinessPurposeTbl businessPurposeTbl;
	private AddressDetailsTbl addressDetailsTbl;
	private UserTbl userTblByRegisteredAgentId;
	private String mbcLegalName;
	private int mbcTotalShares;
	private String mbcPhone;
	private String mbcFax;
	private String mbcPocEmail;
	private String mbcWebUrl;
	private char raWrittenConfirmFlag;
	private char raConsentFlag;
	private BigDecimal applicationFeeAmt;
	private char applicationFeePaidFlag;
	private Date createdDatetime;

	public MbcTempTbl() {
	}

	public MbcTempTbl(int mbcTempId, String mbcLegalName, int mbcTotalShares, String mbcPhone, String mbcFax,
			String mbcPocEmail, String mbcWebUrl, char raWrittenConfirmFlag, char raConsentFlag,
			BigDecimal applicationFeeAmt, char applicationFeePaidFlag, Date createdDatetime) {
		this.mbcTempId = mbcTempId;
		this.mbcLegalName = mbcLegalName;
		this.mbcTotalShares = mbcTotalShares;
		this.mbcPhone = mbcPhone;
		this.mbcFax = mbcFax;
		this.mbcPocEmail = mbcPocEmail;
		this.mbcWebUrl = mbcWebUrl;
		this.raWrittenConfirmFlag = raWrittenConfirmFlag;
		this.raConsentFlag = raConsentFlag;
		this.applicationFeeAmt = applicationFeeAmt;
		this.applicationFeePaidFlag = applicationFeePaidFlag;
		this.createdDatetime = createdDatetime;
	}

	public MbcTempTbl(int mbcTempId, ParticipantShareholderTbl participantShareholderTbl, UserTbl userTblByCreatedBy,
			PrincipalShareholderTbl principalShareholderTbl, BusinessPurposeTbl businessPurposeTbl,
			AddressDetailsTbl addressDetailsTbl, UserTbl userTblByRegisteredAgentId, String mbcLegalName,
			int mbcTotalShares, String mbcPhone, String mbcFax, String mbcPocEmail, String mbcWebUrl,
			char raWrittenConfirmFlag, char raConsentFlag, BigDecimal applicationFeeAmt, char applicationFeePaidFlag,
			Date createdDatetime) {
		this.mbcTempId = mbcTempId;
		this.participantShareholderTbl = participantShareholderTbl;
		this.userTblByCreatedBy = userTblByCreatedBy;
		this.principalShareholderTbl = principalShareholderTbl;
		this.businessPurposeTbl = businessPurposeTbl;
		this.addressDetailsTbl = addressDetailsTbl;
		this.userTblByRegisteredAgentId = userTblByRegisteredAgentId;
		this.mbcLegalName = mbcLegalName;
		this.mbcTotalShares = mbcTotalShares;
		this.mbcPhone = mbcPhone;
		this.mbcFax = mbcFax;
		this.mbcPocEmail = mbcPocEmail;
		this.mbcWebUrl = mbcWebUrl;
		this.raWrittenConfirmFlag = raWrittenConfirmFlag;
		this.raConsentFlag = raConsentFlag;
		this.applicationFeeAmt = applicationFeeAmt;
		this.applicationFeePaidFlag = applicationFeePaidFlag;
		this.createdDatetime = createdDatetime;
	}

	@Id
	@GeneratedValue
	@Column(name = "MBC_TEMP_ID", unique = true, nullable = false)
	public int getMbcTempId() {
		return this.mbcTempId;
	}

	public void setMbcTempId(int mbcTempId) {
		this.mbcTempId = mbcTempId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARTICIPANT_SHAREHOLDER_ID")
	public ParticipantShareholderTbl getParticipantShareholderTbl() {
		return this.participantShareholderTbl;
	}

	public void setParticipantShareholderTbl(ParticipantShareholderTbl participantShareholderTbl) {
		this.participantShareholderTbl = participantShareholderTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public UserTbl getUserTblByCreatedBy() {
		return this.userTblByCreatedBy;
	}

	public void setUserTblByCreatedBy(UserTbl userTblByCreatedBy) {
		this.userTblByCreatedBy = userTblByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRINCIPAL_SHAREHOLDER_ID")
	public PrincipalShareholderTbl getPrincipalShareholderTbl() {
		return this.principalShareholderTbl;
	}

	public void setPrincipalShareholderTbl(PrincipalShareholderTbl principalShareholderTbl) {
		this.principalShareholderTbl = principalShareholderTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_PURPOSE_ID")
	public BusinessPurposeTbl getBusinessPurposeTbl() {
		return this.businessPurposeTbl;
	}

	public void setBusinessPurposeTbl(BusinessPurposeTbl businessPurposeTbl) {
		this.businessPurposeTbl = businessPurposeTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_DETAILS_ID")
	public AddressDetailsTbl getAddressDetailsTbl() {
		return this.addressDetailsTbl;
	}

	public void setAddressDetailsTbl(AddressDetailsTbl addressDetailsTbl) {
		this.addressDetailsTbl = addressDetailsTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGISTERED_AGENT_ID")
	public UserTbl getUserTblByRegisteredAgentId() {
		return this.userTblByRegisteredAgentId;
	}

	public void setUserTblByRegisteredAgentId(UserTbl userTblByRegisteredAgentId) {
		this.userTblByRegisteredAgentId = userTblByRegisteredAgentId;
	}

	@Column(name = "MBC_LEGAL_NAME", nullable = false, length = 45)
	public String getMbcLegalName() {
		return this.mbcLegalName;
	}

	public void setMbcLegalName(String mbcLegalName) {
		this.mbcLegalName = mbcLegalName;
	}

	@Column(name = "MBC_TOTAL_SHARES", nullable = false)
	public int getMbcTotalShares() {
		return this.mbcTotalShares;
	}

	public void setMbcTotalShares(int mbcTotalShares) {
		this.mbcTotalShares = mbcTotalShares;
	}

	@Column(name = "MBC_PHONE", nullable = false, length = 15)
	public String getMbcPhone() {
		return this.mbcPhone;
	}

	public void setMbcPhone(String mbcPhone) {
		this.mbcPhone = mbcPhone;
	}

	@Column(name = "MBC_FAX", nullable = false, length = 15)
	public String getMbcFax() {
		return this.mbcFax;
	}

	public void setMbcFax(String mbcFax) {
		this.mbcFax = mbcFax;
	}

	@Column(name = "MBC_POC_EMAIL", nullable = false, length = 30)
	public String getMbcPocEmail() {
		return this.mbcPocEmail;
	}

	public void setMbcPocEmail(String mbcPocEmail) {
		this.mbcPocEmail = mbcPocEmail;
	}

	@Column(name = "MBC_WEB_URL", nullable = false, length = 30)
	public String getMbcWebUrl() {
		return this.mbcWebUrl;
	}

	public void setMbcWebUrl(String mbcWebUrl) {
		this.mbcWebUrl = mbcWebUrl;
	}

	@Column(name = "RA_WRITTEN_CONFIRM_FLAG", nullable = false, length = 1)
	public char getRaWrittenConfirmFlag() {
		return this.raWrittenConfirmFlag;
	}

	public void setRaWrittenConfirmFlag(char raWrittenConfirmFlag) {
		this.raWrittenConfirmFlag = raWrittenConfirmFlag;
	}

	@Column(name = "RA_CONSENT_FLAG", nullable = false, length = 1)
	public char getRaConsentFlag() {
		return this.raConsentFlag;
	}

	public void setRaConsentFlag(char raConsentFlag) {
		this.raConsentFlag = raConsentFlag;
	}

	@Column(name = "APPLICATION_FEE_AMT", nullable = false, precision = 18)
	public BigDecimal getApplicationFeeAmt() {
		return this.applicationFeeAmt;
	}

	public void setApplicationFeeAmt(BigDecimal applicationFeeAmt) {
		this.applicationFeeAmt = applicationFeeAmt;
	}

	@Column(name = "APPLICATION_FEE_PAID_FLAG", nullable = false, length = 1)
	public char getApplicationFeePaidFlag() {
		return this.applicationFeePaidFlag;
	}

	public void setApplicationFeePaidFlag(char applicationFeePaidFlag) {
		this.applicationFeePaidFlag = applicationFeePaidFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

}
