package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.sciits.blockbuster.model.BaseData;

/**
 * MbcTbl generated by hbm2java
 */
@Entity
@Table(name = "MBC_TBL")
public class MbcTbl extends BaseData {

	private int mbcId;
	private UserTbl userTblByVoluntaryLiquidatorId;
	private FscLegislationTbl fscLegislationTbl;
	private ParticipantShareholderTbl participantShareholderTbl;
	private UserTbl userTblByCreatedBy;
	private PrincipalShareholderTbl principalShareholderTbl;
	private BusinessPurposeTbl businessPurposeTbl;
	private AddressDetailsTbl addressDetailsTbl;
	private UserTbl userTblByRegisteredAgentId;
	private String mbcLegalName;
	private int mbcUniqueId;
	private int mbcTotalShares;
	private char mbcActiveFlag;
	private String mbcPhone;
	private String mbcFax;
	private String mbcPocEmail;
	private String mbcWebUrl;
	private char raWrittenConfirmFlag;
	private char raConsentFlag;
	private String mbcNumber;
	private char mbcFinRegFlag;
	private BigDecimal mbcGrossAssets;
	private int mbcNumberEmployees;
	private BigDecimal applicationFeeAmt;
	private char applicationFeePaidFlag;
	private BigDecimal registrationFeeAmt;
	private char registrationFeePaidFlag;
	private Date raChangeRequestDate;
	private Character regulatedByFsc;
	private Date createdDatetime;
	
	
	//private Set<ParticipantShareholderTbl> participantShareholderTbls = new HashSet<ParticipantShareholderTbl>(0);
	private Set<MbcCharterTbl> mbcCharterTbls = new HashSet<MbcCharterTbl>(0);
	//private Set<PrincipalShareholderTbl> principalShareholderTbls = new HashSet<PrincipalShareholderTbl>(0);

	public MbcTbl() {
	}

	public MbcTbl(int mbcId, UserTbl userTblByCreatedBy, BusinessPurposeTbl businessPurposeTbl,
			AddressDetailsTbl addressDetailsTbl, UserTbl userTblByRegisteredAgentId, String mbcLegalName,
			int mbcUniqueId, int mbcTotalShares, char mbcActiveFlag, String mbcPhone, String mbcFax, String mbcPocEmail,
			String mbcWebUrl, char raWrittenConfirmFlag, char raConsentFlag, String mbcNumber, char mbcFinRegFlag,
			BigDecimal mbcGrossAssets, int mbcNumberEmployees, BigDecimal applicationFeeAmt,
			char applicationFeePaidFlag, BigDecimal registrationFeeAmt, char registrationFeePaidFlag,
			Date createdDatetime) {
		this.mbcId = mbcId;
		this.userTblByCreatedBy = userTblByCreatedBy;
		this.businessPurposeTbl = businessPurposeTbl;
		this.addressDetailsTbl = addressDetailsTbl;
		this.userTblByRegisteredAgentId = userTblByRegisteredAgentId;
		this.mbcLegalName = mbcLegalName;
		this.mbcUniqueId = mbcUniqueId;
		this.mbcTotalShares = mbcTotalShares;
		this.mbcActiveFlag = mbcActiveFlag;
		this.mbcPhone = mbcPhone;
		this.mbcFax = mbcFax;
		this.mbcPocEmail = mbcPocEmail;
		this.mbcWebUrl = mbcWebUrl;
		this.raWrittenConfirmFlag = raWrittenConfirmFlag;
		this.raConsentFlag = raConsentFlag;
		this.mbcNumber = mbcNumber;
		this.mbcFinRegFlag = mbcFinRegFlag;
		this.mbcGrossAssets = mbcGrossAssets;
		this.mbcNumberEmployees = mbcNumberEmployees;
		this.applicationFeeAmt = applicationFeeAmt;
		this.applicationFeePaidFlag = applicationFeePaidFlag;
		this.registrationFeeAmt = registrationFeeAmt;
		this.registrationFeePaidFlag = registrationFeePaidFlag;
		this.createdDatetime = createdDatetime;
	}

	public MbcTbl(int mbcId, UserTbl userTblByVoluntaryLiquidatorId, FscLegislationTbl fscLegislationTbl,
			ParticipantShareholderTbl participantShareholderTbl,
			UserTbl userTblByCreatedBy,
			PrincipalShareholderTbl principalShareholderTbl,
			BusinessPurposeTbl businessPurposeTbl,
			AddressDetailsTbl addressDetailsTbl, UserTbl userTblByRegisteredAgentId, String mbcLegalName,
			int mbcUniqueId, int mbcTotalShares, char mbcActiveFlag, String mbcPhone, String mbcFax, String mbcPocEmail,
			String mbcWebUrl, char raWrittenConfirmFlag, char raConsentFlag, String mbcNumber, char mbcFinRegFlag,
			BigDecimal mbcGrossAssets, int mbcNumberEmployees, BigDecimal applicationFeeAmt,
			char applicationFeePaidFlag, BigDecimal registrationFeeAmt, char registrationFeePaidFlag,
			Date raChangeRequestDate, Character regulatedByFsc, Date createdDatetime,
			 Set<MbcCharterTbl> mbcCharterTbls
			) {
		this.mbcId = mbcId;
		this.userTblByVoluntaryLiquidatorId = userTblByVoluntaryLiquidatorId;
		this.fscLegislationTbl = fscLegislationTbl;
		this.participantShareholderTbl = participantShareholderTbl;
		this.userTblByCreatedBy = userTblByCreatedBy;
		this.principalShareholderTbl = principalShareholderTbl;
		this.businessPurposeTbl = businessPurposeTbl;
		this.addressDetailsTbl = addressDetailsTbl;
		this.userTblByRegisteredAgentId = userTblByRegisteredAgentId;
		this.mbcLegalName = mbcLegalName;
		this.mbcUniqueId = mbcUniqueId;
		this.mbcTotalShares = mbcTotalShares;
		this.mbcActiveFlag = mbcActiveFlag;
		this.mbcPhone = mbcPhone;
		this.mbcFax = mbcFax;
		this.mbcPocEmail = mbcPocEmail;
		this.mbcWebUrl = mbcWebUrl;
		this.raWrittenConfirmFlag = raWrittenConfirmFlag;
		this.raConsentFlag = raConsentFlag;
		this.mbcNumber = mbcNumber;
		this.mbcFinRegFlag = mbcFinRegFlag;
		this.mbcGrossAssets = mbcGrossAssets;
		this.mbcNumberEmployees = mbcNumberEmployees;
		this.applicationFeeAmt = applicationFeeAmt;
		this.applicationFeePaidFlag = applicationFeePaidFlag;
		this.registrationFeeAmt = registrationFeeAmt;
		this.registrationFeePaidFlag = registrationFeePaidFlag;
		this.raChangeRequestDate = raChangeRequestDate;
		this.regulatedByFsc = regulatedByFsc;
		this.createdDatetime = createdDatetime;
		//this.participantShareholderTbls = participantShareholderTbls;
		this.mbcCharterTbls = mbcCharterTbls;
		//this.principalShareholderTbls = principalShareholderTbls;
	}

	@Id
	@GeneratedValue
	@Column(name = "MBC_ID", unique = true, nullable = false)
	public int getMbcId() {
		return this.mbcId;
	}

	public void setMbcId(int mbcId) {
		this.mbcId = mbcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VOLUNTARY_LIQUIDATOR_ID")
	public UserTbl getUserTblByVoluntaryLiquidatorId() {
		return this.userTblByVoluntaryLiquidatorId;
	}

	public void setUserTblByVoluntaryLiquidatorId(UserTbl userTblByVoluntaryLiquidatorId) {
		this.userTblByVoluntaryLiquidatorId = userTblByVoluntaryLiquidatorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FSC_LEGISLATION_ID")
	public FscLegislationTbl getFscLegislationTbl() {
		return this.fscLegislationTbl;
	}

	public void setFscLegislationTbl(FscLegislationTbl fscLegislationTbl) {
		this.fscLegislationTbl = fscLegislationTbl;
	}
	@Transient
	public ParticipantShareholderTbl getParticipantShareholderTbl() {
		return this.participantShareholderTbl;
	}

	@Transient
	public void setParticipantShareholderTbl(ParticipantShareholderTbl participantShareholderTbl) {
		this.participantShareholderTbl = participantShareholderTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", nullable = false)
	public UserTbl getUserTblByCreatedBy() {
		return this.userTblByCreatedBy;
	}

	public void setUserTblByCreatedBy(UserTbl userTblByCreatedBy) {
		this.userTblByCreatedBy = userTblByCreatedBy;
	}

	@Transient
	public PrincipalShareholderTbl getPrincipalShareholderTbl() {
		return this.principalShareholderTbl;
	}

	@Transient
	public void setPrincipalShareholderTbl(PrincipalShareholderTbl principalShareholderTbl) {
		this.principalShareholderTbl = principalShareholderTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_PURPOSE_ID", nullable = false)
	public BusinessPurposeTbl getBusinessPurposeTbl() {
		return this.businessPurposeTbl;
	}

	public void setBusinessPurposeTbl(BusinessPurposeTbl businessPurposeTbl) {
		this.businessPurposeTbl = businessPurposeTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_DETAILS_ID", nullable = false)
	public AddressDetailsTbl getAddressDetailsTbl() {
		return this.addressDetailsTbl;
	}

	public void setAddressDetailsTbl(AddressDetailsTbl addressDetailsTbl) {
		this.addressDetailsTbl = addressDetailsTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGISTERED_AGENT_ID", nullable = false)
	public UserTbl getUserTblByRegisteredAgentId() {
		return this.userTblByRegisteredAgentId;
	}

	public void setUserTblByRegisteredAgentId(UserTbl userTblByRegisteredAgentId) {
		this.userTblByRegisteredAgentId = userTblByRegisteredAgentId;
	}

	@Column(name = "MBC_LEGAL_NAME", nullable = false, length = 45)
	public String getMbcLegalName() {
		return this.mbcLegalName;
	}

	public void setMbcLegalName(String mbcLegalName) {
		this.mbcLegalName = mbcLegalName;
	}

	@Column(name = "MBC_UNIQUE_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getMbcUniqueId() {
		return this.mbcUniqueId;
	}

	public void setMbcUniqueId(int mbcUniqueId) {
		this.mbcUniqueId = mbcUniqueId;
	}

	@Column(name = "MBC_TOTAL_SHARES", nullable = false)
	public int getMbcTotalShares() {
		return this.mbcTotalShares;
	}

	public void setMbcTotalShares(int mbcTotalShares) {
		this.mbcTotalShares = mbcTotalShares;
	}

	@Column(name = "MBC_ACTIVE_FLAG", nullable = false, length = 1)
	public char getMbcActiveFlag() {
		return this.mbcActiveFlag;
	}

	public void setMbcActiveFlag(char mbcActiveFlag) {
		this.mbcActiveFlag = mbcActiveFlag;
	}

	@Column(name = "MBC_PHONE", nullable = false, length = 15)
	public String getMbcPhone() {
		return this.mbcPhone;
	}

	public void setMbcPhone(String mbcPhone) {
		this.mbcPhone = mbcPhone;
	}

	@Column(name = "MBC_FAX", nullable = false, length = 15)
	public String getMbcFax() {
		return this.mbcFax;
	}

	public void setMbcFax(String mbcFax) {
		this.mbcFax = mbcFax;
	}

	@Column(name = "MBC_POC_EMAIL", nullable = false, length = 30)
	public String getMbcPocEmail() {
		return this.mbcPocEmail;
	}

	public void setMbcPocEmail(String mbcPocEmail) {
		this.mbcPocEmail = mbcPocEmail;
	}

	@Column(name = "MBC_WEB_URL", nullable = false, length = 30)
	public String getMbcWebUrl() {
		return this.mbcWebUrl;
	}

	public void setMbcWebUrl(String mbcWebUrl) {
		this.mbcWebUrl = mbcWebUrl;
	}

	@Column(name = "RA_WRITTEN_CONFIRM_FLAG", nullable = false, length = 1)
	public char getRaWrittenConfirmFlag() {
		return this.raWrittenConfirmFlag;
	}

	public void setRaWrittenConfirmFlag(char raWrittenConfirmFlag) {
		this.raWrittenConfirmFlag = raWrittenConfirmFlag;
	}

	@Column(name = "RA_CONSENT_FLAG", nullable = false, length = 1)
	public char getRaConsentFlag() {
		return this.raConsentFlag;
	}

	public void setRaConsentFlag(char raConsentFlag) {
		this.raConsentFlag = raConsentFlag;
	}

	@Column(name = "MBC_NUMBER", unique = true, nullable = false, length = 50)
	public String getMbcNumber() {
		return this.mbcNumber;
	}

	public void setMbcNumber(String mbcNumber) {
		this.mbcNumber = mbcNumber;
	}

	@Column(name = "MBC_FIN_REG_FLAG", nullable = false, length = 1)
	public char getMbcFinRegFlag() {
		return this.mbcFinRegFlag;
	}

	public void setMbcFinRegFlag(char mbcFinRegFlag) {
		this.mbcFinRegFlag = mbcFinRegFlag;
	}

	@Column(name = "MBC_GROSS_ASSETS", nullable = false, precision = 18)
	public BigDecimal getMbcGrossAssets() {
		return this.mbcGrossAssets;
	}

	public void setMbcGrossAssets(BigDecimal mbcGrossAssets) {
		this.mbcGrossAssets = mbcGrossAssets;
	}

	@Column(name = "MBC_NUMBER_EMPLOYEES", nullable = false)
	public int getMbcNumberEmployees() {
		return this.mbcNumberEmployees;
	}

	public void setMbcNumberEmployees(int mbcNumberEmployees) {
		this.mbcNumberEmployees = mbcNumberEmployees;
	}

	@Column(name = "APPLICATION_FEE_AMT", nullable = false, precision = 18)
	public BigDecimal getApplicationFeeAmt() {
		return this.applicationFeeAmt;
	}

	public void setApplicationFeeAmt(BigDecimal applicationFeeAmt) {
		this.applicationFeeAmt = applicationFeeAmt;
	}

	@Column(name = "APPLICATION_FEE_PAID_FLAG", nullable = false, length = 1)
	public char getApplicationFeePaidFlag() {
		return this.applicationFeePaidFlag;
	}

	public void setApplicationFeePaidFlag(char applicationFeePaidFlag) {
		this.applicationFeePaidFlag = applicationFeePaidFlag;
	}

	@Column(name = "REGISTRATION_FEE_AMT", nullable = false, precision = 18)
	public BigDecimal getRegistrationFeeAmt() {
		return this.registrationFeeAmt;
	}

	public void setRegistrationFeeAmt(BigDecimal registrationFeeAmt) {
		this.registrationFeeAmt = registrationFeeAmt;
	}

	@Column(name = "REGISTRATION_FEE_PAID_FLAG", nullable = false, length = 1)
	public char getRegistrationFeePaidFlag() {
		return this.registrationFeePaidFlag;
	}

	public void setRegistrationFeePaidFlag(char registrationFeePaidFlag) {
		this.registrationFeePaidFlag = registrationFeePaidFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RA_CHANGE_REQUEST_DATE", length = 23)
	public Date getRaChangeRequestDate() {
		return this.raChangeRequestDate;
	}

	public void setRaChangeRequestDate(Date raChangeRequestDate) {
		this.raChangeRequestDate = raChangeRequestDate;
	}

	@Column(name = "REGULATED_BY_FSC", length = 1)
	public Character getRegulatedByFsc() {
		return this.regulatedByFsc;
	}

	public void setRegulatedByFsc(Character regulatedByFsc) {
		this.regulatedByFsc = regulatedByFsc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbcTbl")
	public Set<MbcCharterTbl> getMbcCharterTbls() {
		return this.mbcCharterTbls;
	}

	public void setMbcCharterTbls(Set<MbcCharterTbl> mbcCharterTbls) {
		this.mbcCharterTbls = mbcCharterTbls;
	}

	

}
