package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sciits.blockbuster.model.BaseData;

/**
 * ParticipantShareholderTbl generated by hbm2java
 */
@Entity
@Table(name = "PARTICIPANT_SHAREHOLDER_TBL")
public class ParticipantShareholderTbl extends BaseData {

	private int participantShareholderId;
	private MbcTbl mbcTbl;
	private CountryTbl countryTbl;
	private UserTbl userTbl;
	private String firstName;
	private String lastName;
	private int totalShares;
	private Date createdDatetime;
	

	public ParticipantShareholderTbl() {
	}

	public ParticipantShareholderTbl(int participantShareholderId, MbcTbl mbcTbl, CountryTbl countryTbl,
			String firstName, String lastName, int totalShares, Date createdDatetime) {
		this.participantShareholderId = participantShareholderId;
		this.mbcTbl = mbcTbl;
		this.countryTbl = countryTbl;
		this.firstName = firstName;
		this.lastName = lastName;
		this.totalShares = totalShares;
		this.createdDatetime = createdDatetime;
	}

	/*public ParticipantShareholderTbl(int participantShareholderId, MbcTbl mbcTbl, CountryTbl countryTbl,
			UserTbl userTbl, String firstName, String lastName, int totalShares, Date createdDatetime,
			Set<MbcTbl> mbcTbls, Set<MbcTempTbl> mbcTempTbls) {
		this.participantShareholderId = participantShareholderId;
		this.mbcTbl = mbcTbl;
		this.countryTbl = countryTbl;
		this.userTbl = userTbl;
		this.firstName = firstName;
		this.lastName = lastName;
		this.totalShares = totalShares;
		this.createdDatetime = createdDatetime;
		this.mbcTbls = mbcTbls;
		this.mbcTempTbls = mbcTempTbls;
	}*/

	@Id
	@GeneratedValue
	@Column(name = "PARTICIPANT_SHAREHOLDER_ID", unique = true, nullable = false)
	public int getParticipantShareholderId() {
		return this.participantShareholderId;
	}

	public void setParticipantShareholderId(int participantShareholderId) {
		this.participantShareholderId = participantShareholderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MBC_ID", nullable = false)
	public MbcTbl getMbcTbl() {
		return this.mbcTbl;
	}

	public void setMbcTbl(MbcTbl mbcTbl) {
		this.mbcTbl = mbcTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_ID", nullable = false)
	public CountryTbl getCountryTbl() {
		return this.countryTbl;
	}

	public void setCountryTbl(CountryTbl countryTbl) {
		this.countryTbl = countryTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "TOTAL_SHARES", nullable = false)
	public int getTotalShares() {
		return this.totalShares;
	}

	public void setTotalShares(int totalShares) {
		this.totalShares = totalShares;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	

}
