
package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.sciits.blockbuster.model.BaseData;
import com.sciits.blockbuster.web.model.WebRoleDetails;

/**
 * RoleTbl generated by hbm2java
 */
@Entity
@Table(name = "ROLE_TBL")
public class RoleTbl extends BaseData {

	private int roleId;
	private String roleCode;
	private String roleDescription;
	private String roleDetails;
	private Date createdDatetime;
	private Set<UserRoleTbl> userRoleTbls = new HashSet<UserRoleTbl>(0);

	public RoleTbl() {
	}

	public RoleTbl(int roleId, String roleCode, String roleDescription, Date createdDatetime) {
		this.roleId = roleId;
		this.roleCode = roleCode;
		this.roleDescription = roleDescription;
		this.createdDatetime = createdDatetime;
	}

	public RoleTbl(int roleId, String roleCode, String roleDescription, String roleDetails, Date createdDatetime,
			Set<UserRoleTbl> userRoleTbls) {
		this.roleId = roleId;
		this.roleCode = roleCode;
		this.roleDescription = roleDescription;
		this.roleDetails = roleDetails;
		this.createdDatetime = createdDatetime;
		this.userRoleTbls = userRoleTbls;
	}

	@Id
	@GeneratedValue
	@Column(name = "ROLE_ID", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "ROLE_CODE", nullable = false, length = 25)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "ROLE_DESCRIPTION", nullable = false, length = 50)
	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	@Column(name = "ROLE_DETAILS")
	public String getRoleDetails() {
		return this.roleDetails;
	}

	public void setRoleDetails(String roleDetails) {
		this.roleDetails = roleDetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleTbl")
	public Set<UserRoleTbl> getUserRoleTbls() {
		return this.userRoleTbls;
	}

	public void setUserRoleTbls(Set<UserRoleTbl> userRoleTbls) {
		this.userRoleTbls = userRoleTbls;
	}
	@Transient
	public WebRoleDetails getWebRoleDetails(){
		WebRoleDetails webRoleDetails = new WebRoleDetails();
		webRoleDetails.setRoleId(roleId);
		webRoleDetails.setRoleCode(roleCode);
		webRoleDetails.setRoleDescription(roleDescription);
		webRoleDetails.setRoleDetails(roleDetails);
		return webRoleDetails;
		
		
	}

}
