package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserTbl generated by hbm2java
 */
@Entity
@Table(name = "USER_TBL")
public class UserTbl implements java.io.Serializable {

	private int userId;
	private String firstName;
	private String lastName;
	private char activeFlag;
	private Date createdDatetime;
	private Set<AddressTypeTbl> addressTypeTbls = new HashSet<AddressTypeTbl>(0);
	private Set<MbcTbl> mbcTblsForVoluntaryLiquidatorId = new HashSet<MbcTbl>(0);
	private Set<ParticipantShareholderTbl> participantShareholderTbls = new HashSet<ParticipantShareholderTbl>(0);
	private Set<BusinessPurposeTbl> businessPurposeTbls = new HashSet<BusinessPurposeTbl>(0);
	private Set<MbcTbl> mbcTblsForRegisteredAgentId = new HashSet<MbcTbl>(0);
	private Set<UserRoleTbl> userRoleTblsForUserId = new HashSet<UserRoleTbl>(0);
	private Set<UserDetailsTbl> userDetailsTblsForCreatedBy = new HashSet<UserDetailsTbl>(0);
	private Set<UserRoleTbl> userRoleTblsForCreatedBy = new HashSet<UserRoleTbl>(0);
	private Set<UserLoginTbl> userLoginTblsForCreatedBy = new HashSet<UserLoginTbl>(0);
	private Set<MbcTempTbl> mbcTempTblsForRegisteredAgentId = new HashSet<MbcTempTbl>(0);
	private Set<UserSignupTbl> userSignupTbls = new HashSet<UserSignupTbl>(0);
	private Set<MbcCharterTbl> mbcCharterTbls = new HashSet<MbcCharterTbl>(0);
	private Set<UserDetailsTbl> userDetailsTblsForUserId = new HashSet<UserDetailsTbl>(0);
	private Set<UserLoginTbl> userLoginTblsForUserId = new HashSet<UserLoginTbl>(0);
	private Set<MbcTbl> mbcTblsForCreatedBy = new HashSet<MbcTbl>(0);
	private Set<FscLegislationTbl> fscLegislationTbls = new HashSet<FscLegislationTbl>(0);
	private Set<AddressDetailsTbl> addressDetailsTbls = new HashSet<AddressDetailsTbl>(0);
	private Set<CountryTbl> countryTbls = new HashSet<CountryTbl>(0);
	private Set<MbcRegistrtionTbl> mbcRegistrtionTbls = new HashSet<MbcRegistrtionTbl>(0);
	private Set<MbcTempTbl> mbcTempTblsForCreatedBy = new HashSet<MbcTempTbl>(0);
	private Set<PrincipalShareholderTbl> principalShareholderTbls = new HashSet<PrincipalShareholderTbl>(0);

	public UserTbl() {
	}

	public UserTbl(int userId, String firstName, String lastName, char activeFlag, Date createdDatetime) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.activeFlag = activeFlag;
		this.createdDatetime = createdDatetime;
	}

	public UserTbl(int userId, String firstName, String lastName, char activeFlag, Date createdDatetime,
			Set<AddressTypeTbl> addressTypeTbls, Set<MbcTbl> mbcTblsForVoluntaryLiquidatorId,
			Set<ParticipantShareholderTbl> participantShareholderTbls, Set<BusinessPurposeTbl> businessPurposeTbls,
			Set<MbcTbl> mbcTblsForRegisteredAgentId, Set<UserRoleTbl> userRoleTblsForUserId,
			Set<UserDetailsTbl> userDetailsTblsForCreatedBy, Set<UserRoleTbl> userRoleTblsForCreatedBy,
			Set<UserLoginTbl> userLoginTblsForCreatedBy, Set<MbcTempTbl> mbcTempTblsForRegisteredAgentId,
			Set<UserSignupTbl> userSignupTbls, Set<MbcCharterTbl> mbcCharterTbls,
			Set<UserDetailsTbl> userDetailsTblsForUserId, Set<UserLoginTbl> userLoginTblsForUserId,
			Set<MbcTbl> mbcTblsForCreatedBy, Set<FscLegislationTbl> fscLegislationTbls,
			Set<AddressDetailsTbl> addressDetailsTbls, Set<CountryTbl> countryTbls,
			Set<MbcRegistrtionTbl> mbcRegistrtionTbls, Set<MbcTempTbl> mbcTempTblsForCreatedBy,
			Set<PrincipalShareholderTbl> principalShareholderTbls) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.activeFlag = activeFlag;
		this.createdDatetime = createdDatetime;
		this.addressTypeTbls = addressTypeTbls;
		this.mbcTblsForVoluntaryLiquidatorId = mbcTblsForVoluntaryLiquidatorId;
		this.participantShareholderTbls = participantShareholderTbls;
		this.businessPurposeTbls = businessPurposeTbls;
		this.mbcTblsForRegisteredAgentId = mbcTblsForRegisteredAgentId;
		this.userRoleTblsForUserId = userRoleTblsForUserId;
		this.userDetailsTblsForCreatedBy = userDetailsTblsForCreatedBy;
		this.userRoleTblsForCreatedBy = userRoleTblsForCreatedBy;
		this.userLoginTblsForCreatedBy = userLoginTblsForCreatedBy;
		this.mbcTempTblsForRegisteredAgentId = mbcTempTblsForRegisteredAgentId;
		this.userSignupTbls = userSignupTbls;
		this.mbcCharterTbls = mbcCharterTbls;
		this.userDetailsTblsForUserId = userDetailsTblsForUserId;
		this.userLoginTblsForUserId = userLoginTblsForUserId;
		this.mbcTblsForCreatedBy = mbcTblsForCreatedBy;
		this.fscLegislationTbls = fscLegislationTbls;
		this.addressDetailsTbls = addressDetailsTbls;
		this.countryTbls = countryTbls;
		this.mbcRegistrtionTbls = mbcRegistrtionTbls;
		this.mbcTempTblsForCreatedBy = mbcTempTblsForCreatedBy;
		this.principalShareholderTbls = principalShareholderTbls;
	}

	@Id
	@GeneratedValue
	@Column(name = "USER_ID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 60)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 60)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "ACTIVE_FLAG", nullable = false, length = 1)
	public char getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(char activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<AddressTypeTbl> getAddressTypeTbls() {
		return this.addressTypeTbls;
	}

	public void setAddressTypeTbls(Set<AddressTypeTbl> addressTypeTbls) {
		this.addressTypeTbls = addressTypeTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByVoluntaryLiquidatorId")
	public Set<MbcTbl> getMbcTblsForVoluntaryLiquidatorId() {
		return this.mbcTblsForVoluntaryLiquidatorId;
	}

	public void setMbcTblsForVoluntaryLiquidatorId(Set<MbcTbl> mbcTblsForVoluntaryLiquidatorId) {
		this.mbcTblsForVoluntaryLiquidatorId = mbcTblsForVoluntaryLiquidatorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<ParticipantShareholderTbl> getParticipantShareholderTbls() {
		return this.participantShareholderTbls;
	}

	public void setParticipantShareholderTbls(Set<ParticipantShareholderTbl> participantShareholderTbls) {
		this.participantShareholderTbls = participantShareholderTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<BusinessPurposeTbl> getBusinessPurposeTbls() {
		return this.businessPurposeTbls;
	}

	public void setBusinessPurposeTbls(Set<BusinessPurposeTbl> businessPurposeTbls) {
		this.businessPurposeTbls = businessPurposeTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByRegisteredAgentId")
	public Set<MbcTbl> getMbcTblsForRegisteredAgentId() {
		return this.mbcTblsForRegisteredAgentId;
	}

	public void setMbcTblsForRegisteredAgentId(Set<MbcTbl> mbcTblsForRegisteredAgentId) {
		this.mbcTblsForRegisteredAgentId = mbcTblsForRegisteredAgentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByUserId")
	public Set<UserRoleTbl> getUserRoleTblsForUserId() {
		return this.userRoleTblsForUserId;
	}

	public void setUserRoleTblsForUserId(Set<UserRoleTbl> userRoleTblsForUserId) {
		this.userRoleTblsForUserId = userRoleTblsForUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByCreatedBy")
	public Set<UserDetailsTbl> getUserDetailsTblsForCreatedBy() {
		return this.userDetailsTblsForCreatedBy;
	}

	public void setUserDetailsTblsForCreatedBy(Set<UserDetailsTbl> userDetailsTblsForCreatedBy) {
		this.userDetailsTblsForCreatedBy = userDetailsTblsForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByCreatedBy")
	public Set<UserRoleTbl> getUserRoleTblsForCreatedBy() {
		return this.userRoleTblsForCreatedBy;
	}

	public void setUserRoleTblsForCreatedBy(Set<UserRoleTbl> userRoleTblsForCreatedBy) {
		this.userRoleTblsForCreatedBy = userRoleTblsForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByCreatedBy")
	public Set<UserLoginTbl> getUserLoginTblsForCreatedBy() {
		return this.userLoginTblsForCreatedBy;
	}

	public void setUserLoginTblsForCreatedBy(Set<UserLoginTbl> userLoginTblsForCreatedBy) {
		this.userLoginTblsForCreatedBy = userLoginTblsForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByRegisteredAgentId")
	public Set<MbcTempTbl> getMbcTempTblsForRegisteredAgentId() {
		return this.mbcTempTblsForRegisteredAgentId;
	}

	public void setMbcTempTblsForRegisteredAgentId(Set<MbcTempTbl> mbcTempTblsForRegisteredAgentId) {
		this.mbcTempTblsForRegisteredAgentId = mbcTempTblsForRegisteredAgentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<UserSignupTbl> getUserSignupTbls() {
		return this.userSignupTbls;
	}

	public void setUserSignupTbls(Set<UserSignupTbl> userSignupTbls) {
		this.userSignupTbls = userSignupTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<MbcCharterTbl> getMbcCharterTbls() {
		return this.mbcCharterTbls;
	}

	public void setMbcCharterTbls(Set<MbcCharterTbl> mbcCharterTbls) {
		this.mbcCharterTbls = mbcCharterTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByUserId")
	public Set<UserDetailsTbl> getUserDetailsTblsForUserId() {
		return this.userDetailsTblsForUserId;
	}

	public void setUserDetailsTblsForUserId(Set<UserDetailsTbl> userDetailsTblsForUserId) {
		this.userDetailsTblsForUserId = userDetailsTblsForUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByUserId")
	public Set<UserLoginTbl> getUserLoginTblsForUserId() {
		return this.userLoginTblsForUserId;
	}

	public void setUserLoginTblsForUserId(Set<UserLoginTbl> userLoginTblsForUserId) {
		this.userLoginTblsForUserId = userLoginTblsForUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByCreatedBy")
	public Set<MbcTbl> getMbcTblsForCreatedBy() {
		return this.mbcTblsForCreatedBy;
	}

	public void setMbcTblsForCreatedBy(Set<MbcTbl> mbcTblsForCreatedBy) {
		this.mbcTblsForCreatedBy = mbcTblsForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<FscLegislationTbl> getFscLegislationTbls() {
		return this.fscLegislationTbls;
	}

	public void setFscLegislationTbls(Set<FscLegislationTbl> fscLegislationTbls) {
		this.fscLegislationTbls = fscLegislationTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<AddressDetailsTbl> getAddressDetailsTbls() {
		return this.addressDetailsTbls;
	}

	public void setAddressDetailsTbls(Set<AddressDetailsTbl> addressDetailsTbls) {
		this.addressDetailsTbls = addressDetailsTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<CountryTbl> getCountryTbls() {
		return this.countryTbls;
	}

	public void setCountryTbls(Set<CountryTbl> countryTbls) {
		this.countryTbls = countryTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<MbcRegistrtionTbl> getMbcRegistrtionTbls() {
		return this.mbcRegistrtionTbls;
	}

	public void setMbcRegistrtionTbls(Set<MbcRegistrtionTbl> mbcRegistrtionTbls) {
		this.mbcRegistrtionTbls = mbcRegistrtionTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTblByCreatedBy")
	public Set<MbcTempTbl> getMbcTempTblsForCreatedBy() {
		return this.mbcTempTblsForCreatedBy;
	}

	public void setMbcTempTblsForCreatedBy(Set<MbcTempTbl> mbcTempTblsForCreatedBy) {
		this.mbcTempTblsForCreatedBy = mbcTempTblsForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTbl")
	public Set<PrincipalShareholderTbl> getPrincipalShareholderTbls() {
		return this.principalShareholderTbls;
	}

	public void setPrincipalShareholderTbls(Set<PrincipalShareholderTbl> principalShareholderTbls) {
		this.principalShareholderTbls = principalShareholderTbls;
	}

}
