package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDetailsTbl generated by hbm2java
 */
@Entity
@Table(name = "USER_DETAILS_TBL")
public class UserDetailsTbl implements java.io.Serializable {

	private int userDetailsId;
	private UserTbl userTblByCreatedBy;
	private AddressDetailsTbl addressDetailsTbl;
	private UserTbl userTblByUserId;
	private String emailAddress;
	private String phone;
	private String fax;
	private String organizationName;
	private Date createdDatetime;

	public UserDetailsTbl() {
	}

	public UserDetailsTbl(int userDetailsId, UserTbl userTblByCreatedBy, AddressDetailsTbl addressDetailsTbl,
			UserTbl userTblByUserId, String emailAddress, String phone, Date createdDatetime) {
		this.userDetailsId = userDetailsId;
		this.userTblByCreatedBy = userTblByCreatedBy;
		this.addressDetailsTbl = addressDetailsTbl;
		this.userTblByUserId = userTblByUserId;
		this.emailAddress = emailAddress;
		this.phone = phone;
		this.createdDatetime = createdDatetime;
	}

	public UserDetailsTbl(int userDetailsId, UserTbl userTblByCreatedBy, AddressDetailsTbl addressDetailsTbl,
			UserTbl userTblByUserId, String emailAddress, String phone, String fax, String organizationName,
			Date createdDatetime) {
		this.userDetailsId = userDetailsId;
		this.userTblByCreatedBy = userTblByCreatedBy;
		this.addressDetailsTbl = addressDetailsTbl;
		this.userTblByUserId = userTblByUserId;
		this.emailAddress = emailAddress;
		this.phone = phone;
		this.fax = fax;
		this.organizationName = organizationName;
		this.createdDatetime = createdDatetime;
	}

	@Id
	@GeneratedValue
	@Column(name = "USER_DETAILS_ID", unique = true, nullable = false)
	public int getUserDetailsId() {
		return this.userDetailsId;
	}

	public void setUserDetailsId(int userDetailsId) {
		this.userDetailsId = userDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", nullable = false)
	public UserTbl getUserTblByCreatedBy() {
		return this.userTblByCreatedBy;
	}

	public void setUserTblByCreatedBy(UserTbl userTblByCreatedBy) {
		this.userTblByCreatedBy = userTblByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_DETAILS_ID", nullable = false)
	public AddressDetailsTbl getAddressDetailsTbl() {
		return this.addressDetailsTbl;
	}

	public void setAddressDetailsTbl(AddressDetailsTbl addressDetailsTbl) {
		this.addressDetailsTbl = addressDetailsTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserTbl getUserTblByUserId() {
		return this.userTblByUserId;
	}

	public void setUserTblByUserId(UserTbl userTblByUserId) {
		this.userTblByUserId = userTblByUserId;
	}

	@Column(name = "EMAIL_ADDRESS", nullable = false)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "PHONE", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "FAX", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "ORGANIZATION_NAME")
	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

}
