package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.sciits.blockbuster.web.model.WebUserLoginDetails;

/**
 * UserLoginTbl generated by hbm2java
 */
@Entity
@Table(name = "USER_LOGIN_TBL")
public class UserLoginTbl implements java.io.Serializable {

	private int userLoginId;
	private UserTbl userTblByCreatedBy;
	private UserTbl userTblByUserId;
	private String username;
	private String password;
	private String passwordQuestions;
	private String passwordAnswer;
	private char isLockedout;
	private Date lastLoginDate;
	private Date createdDatetime;
	private Date lastPwdChangeDate;

	public UserLoginTbl() {
	}

	public UserLoginTbl(int userLoginId, UserTbl userTblByCreatedBy, UserTbl userTblByUserId, String username,
			String password, String passwordQuestions, String passwordAnswer, char isLockedout,
			Date lastLoginDate, Date createdDatetime, Date lastPwdChangeDate) {
		this.userLoginId = userLoginId;
		this.userTblByCreatedBy = userTblByCreatedBy;
		this.userTblByUserId = userTblByUserId;
		this.username = username;
		this.password = password;
		this.passwordQuestions = passwordQuestions;
		this.passwordAnswer = passwordAnswer;
		this.isLockedout = isLockedout;
		this.lastLoginDate = lastLoginDate;
		this.createdDatetime = createdDatetime;
		this.lastPwdChangeDate = lastPwdChangeDate;
	}

	@Id
	@GeneratedValue
	@Column(name = "USER_LOGIN_ID", unique = true, nullable = false)
	public int getUserLoginId() {
		return this.userLoginId;
	}

	public void setUserLoginId(int userLoginId) {
		this.userLoginId = userLoginId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", nullable = false)
	public UserTbl getUserTblByCreatedBy() {
		return this.userTblByCreatedBy;
	}

	public void setUserTblByCreatedBy(UserTbl userTblByCreatedBy) {
		this.userTblByCreatedBy = userTblByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserTbl getUserTblByUserId() {
		return this.userTblByUserId;
	}

	public void setUserTblByUserId(UserTbl userTblByUserId) {
		this.userTblByUserId = userTblByUserId;
	}

	@Column(name = "USERNAME", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "PASSWORD_QUESTIONS", nullable = false)
	public String getPasswordQuestions() {
		return this.passwordQuestions;
	}

	public void setPasswordQuestions(String passwordQuestions) {
		this.passwordQuestions = passwordQuestions;
	}

	@Column(name = "PASSWORD_ANSWER", nullable = false)
	public String getPasswordAnswer() {
		return this.passwordAnswer;
	}

	public void setPasswordAnswer(String passwordAnswer) {
		this.passwordAnswer = passwordAnswer;
	}

	@Column(name = "IS_LOCKEDOUT", nullable = false, length = 1)
	public char getIsLockedout() {
		return this.isLockedout;
	}

	public void setIsLockedout(char isLockedout) {
		this.isLockedout = isLockedout;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_LOGIN_DATE", nullable = false, length = 23)
	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_PWD_CHANGE_DATE", nullable = false, length = 23)
	public Date getLastPwdChangeDate() {
		return this.lastPwdChangeDate;
	}

	public void setLastPwdChangeDate(Date lastPwdChangeDate) {
		this.lastPwdChangeDate = lastPwdChangeDate;
	}
	
	@Transient
	public WebUserLoginDetails getWebUserLoginDetails() {
		WebUserLoginDetails wuld = new WebUserLoginDetails();
		wuld.setUserDetailsId(userLoginId);
		wuld.setUsername(username);
		wuld.setLastLoginDate(lastLoginDate);
		//wuld.setFirstName(userTblByUserId.getFirstName());
		//wuld.setLastName(userTblByUserId.getLastName());
		return wuld;
	}

}
