package com.sciits.blockbuster.dao.model;
// Generated Mar 14, 2017 4:58:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRoleTbl generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLE_TBL")
public class UserRoleTbl implements java.io.Serializable {

	private int userRoleId;
	private RoleTbl roleTbl;
	private UserTbl userTblByCreatedBy;
	private UserTbl userTblByUserId;
	private Date createdDatetime;

	public UserRoleTbl() {
	}

	public UserRoleTbl(int userRoleId, RoleTbl roleTbl, UserTbl userTblByUserId, Date createdDatetime) {
		this.userRoleId = userRoleId;
		this.roleTbl = roleTbl;
		this.userTblByUserId = userTblByUserId;
		this.createdDatetime = createdDatetime;
	}

	public UserRoleTbl(int userRoleId, RoleTbl roleTbl, UserTbl userTblByCreatedBy, UserTbl userTblByUserId,
			Date createdDatetime) {
		this.userRoleId = userRoleId;
		this.roleTbl = roleTbl;
		this.userTblByCreatedBy = userTblByCreatedBy;
		this.userTblByUserId = userTblByUserId;
		this.createdDatetime = createdDatetime;
	}

	@Id
	@GeneratedValue
	@Column(name = "USER_ROLE_ID", unique = true, nullable = false)
	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID", nullable = false)
	public RoleTbl getRoleTbl() {
		return this.roleTbl;
	}

	public void setRoleTbl(RoleTbl roleTbl) {
		this.roleTbl = roleTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public UserTbl getUserTblByCreatedBy() {
		return this.userTblByCreatedBy;
	}

	public void setUserTblByCreatedBy(UserTbl userTblByCreatedBy) {
		this.userTblByCreatedBy = userTblByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserTbl getUserTblByUserId() {
		return this.userTblByUserId;
	}

	public void setUserTblByUserId(UserTbl userTblByUserId) {
		this.userTblByUserId = userTblByUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATETIME", nullable = false, length = 23)
	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

}
